/*
 * This file is generated by jOOQ.
*/
package io.github.chavesrodolfo.books.generatedclasses.tables;


import io.github.chavesrodolfo.books.generatedclasses.Keys;
import io.github.chavesrodolfo.books.generatedclasses.Public;
import io.github.chavesrodolfo.books.generatedclasses.tables.records.BookAuthorRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookAuthor extends TableImpl<BookAuthorRecord> {

    private static final long serialVersionUID = -129856061;

    /**
     * The reference instance of <code>PUBLIC.BOOK_AUTHOR</code>
     */
    public static final BookAuthor BOOK_AUTHOR = new BookAuthor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookAuthorRecord> getRecordType() {
        return BookAuthorRecord.class;
    }

    /**
     * The column <code>PUBLIC.BOOK_AUTHOR.AUTHOR_ID</code>.
     */
    public final TableField<BookAuthorRecord, Integer> AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.BOOK_AUTHOR.BOOK_ID</code>.
     */
    public final TableField<BookAuthorRecord, Integer> BOOK_ID = createField("BOOK_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.BOOK_AUTHOR</code> table reference
     */
    public BookAuthor() {
        this("BOOK_AUTHOR", null);
    }

    /**
     * Create an aliased <code>PUBLIC.BOOK_AUTHOR</code> table reference
     */
    public BookAuthor(String alias) {
        this(alias, BOOK_AUTHOR);
    }

    private BookAuthor(String alias, Table<BookAuthorRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookAuthor(String alias, Table<BookAuthorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BookAuthorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BookAuthorRecord, ?>>asList(Keys.FK_AUTHOR, Keys.FK_BOOK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookAuthor as(String alias) {
        return new BookAuthor(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookAuthor rename(String name) {
        return new BookAuthor(name, null);
    }
}
