/*
 * This file is generated by jOOQ.
*/
package io.github.chavesrodolfo.books.generatedclasses.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = -1776508760;

    private Integer bookId;
    private String  isbn;
    private String  title;
    private String  subtitle;
    private Date    published;
    private String  publisher;
    private Integer pages;
    private String  description;
    private Boolean instock;

    public Book() {}

    public Book(Book value) {
        this.bookId = value.bookId;
        this.isbn = value.isbn;
        this.title = value.title;
        this.subtitle = value.subtitle;
        this.published = value.published;
        this.publisher = value.publisher;
        this.pages = value.pages;
        this.description = value.description;
        this.instock = value.instock;
    }

    public Book(
        Integer bookId,
        String  isbn,
        String  title,
        String  subtitle,
        Date    published,
        String  publisher,
        Integer pages,
        String  description,
        Boolean instock
    ) {
        this.bookId = bookId;
        this.isbn = isbn;
        this.title = title;
        this.subtitle = subtitle;
        this.published = published;
        this.publisher = publisher;
        this.pages = pages;
        this.description = description;
        this.instock = instock;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubtitle() {
        return this.subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    public Date getPublished() {
        return this.published;
    }

    public void setPublished(Date published) {
        this.published = published;
    }

    public String getPublisher() {
        return this.publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public Integer getPages() {
        return this.pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getInstock() {
        return this.instock;
    }

    public void setInstock(Boolean instock) {
        this.instock = instock;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Book other = (Book) obj;
        if (bookId == null) {
            if (other.bookId != null)
                return false;
        }
        else if (!bookId.equals(other.bookId))
            return false;
        if (isbn == null) {
            if (other.isbn != null)
                return false;
        }
        else if (!isbn.equals(other.isbn))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (subtitle == null) {
            if (other.subtitle != null)
                return false;
        }
        else if (!subtitle.equals(other.subtitle))
            return false;
        if (published == null) {
            if (other.published != null)
                return false;
        }
        else if (!published.equals(other.published))
            return false;
        if (publisher == null) {
            if (other.publisher != null)
                return false;
        }
        else if (!publisher.equals(other.publisher))
            return false;
        if (pages == null) {
            if (other.pages != null)
                return false;
        }
        else if (!pages.equals(other.pages))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (instock == null) {
            if (other.instock != null)
                return false;
        }
        else if (!instock.equals(other.instock))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((bookId == null) ? 0 : bookId.hashCode());
        result = prime * result + ((isbn == null) ? 0 : isbn.hashCode());
        result = prime * result + ((title == null) ? 0 : title.hashCode());
        result = prime * result + ((subtitle == null) ? 0 : subtitle.hashCode());
        result = prime * result + ((published == null) ? 0 : published.hashCode());
        result = prime * result + ((publisher == null) ? 0 : publisher.hashCode());
        result = prime * result + ((pages == null) ? 0 : pages.hashCode());
        result = prime * result + ((description == null) ? 0 : description.hashCode());
        result = prime * result + ((instock == null) ? 0 : instock.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(bookId);
        sb.append(", ").append(isbn);
        sb.append(", ").append(title);
        sb.append(", ").append(subtitle);
        sb.append(", ").append(published);
        sb.append(", ").append(publisher);
        sb.append(", ").append(pages);
        sb.append(", ").append(description);
        sb.append(", ").append(instock);

        sb.append(")");
        return sb.toString();
    }
}
